// app/layout.js (Server Component)
import "../styles/globals.css";
import Providers from "./providers";
import LayoutClient from "./layoutClient";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* LayoutClient will handle conditional nav/footer */}
          <LayoutClient>{children}</LayoutClient>
        </Providers>
      </body>
    </html>
  );
}
